# Generated by Django 4.2.3 on 2023-08-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbook',
            name='user',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbs_per_100g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('meat', 'Meat'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='kcal_per_100g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein_per_100g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
